<?xml version="1.0" encoding="utf-8"?>
<testsuite failures="1" name="c8y_jwt_token_retrieval" skipped="0" tests="1" time="2.08" timestamp="2022-04-27T10:33:26">
	<testcase classname="ValidateJWTTokenRetrieval" name="c8y_jwt_token_retrieval">
		<failure message="BLOCKED: sudo&lt;tedge_connect_c8y&gt; returned non-zero exit code 1" type="BLOCKED"/>
		<system-out>10:33:24 INFO  ==============================================================
10:33:24 INFO  Id:    c8y_jwt_token_retrieval
10:33:24 INFO  Dir:   cloud_c8y/
10:33:24 INFO  Title: Validate the Cumulocity JWT Token Retrieval feature
10:33:24 INFO  ==============================================================
10:33:24 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:33:25 WARN  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 1
10:33:25 INFO  Contents of tedge_connect_c8y.err: 
  Error: failed to connect Cumulocity cloud.
  Caused by:
      A value for `c8y.url` is missing.
          A value can be set with `tedge config set c8y.url &lt;value&gt;`
  -----

10:33:25 WARN  sudo&lt;tedge_connect_c8y&gt; returned non-zero exit code 1 ... blocked [environment_tedge.py:58,run.py:31]
10:33:25 WARN  Aborted test due to BLOCKED outcome
10:33:25 INFO  
10:33:25 INFO  cleanup:
10:33:26 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
10:33:26 INFO  
10:33:26 INFO  Test duration: 2.08 secs
10:33:26 INFO  Test final outcome:  BLOCKED
10:33:26 INFO  Test outcome reason: sudo&lt;tedge_connect_c8y&gt; returned non-zero exit code 1
10:33:26 INFO  
</system-out>
	</testcase>
</testsuite>
