<?xml version="1.0" encoding="utf-8"?>
<testsuite failures="1" name="SoftwareManagement.Plugin.apama_plugin_install" skipped="0" tests="1" time="1.45" timestamp="2022-04-27T18:29:17">
	<testcase classname="ApamaPluginInstallTest" name="SoftwareManagement.Plugin.apama_plugin_install">
		<failure message="BLOCKED: sudo&lt;plugin_install&gt; returned non-zero exit code 2 (+2 other failures)" type="BLOCKED"/>
		<system-out>18:29:15 INFO  ==============================================================
18:29:15 INFO  Id:    SoftwareManagement.Plugin.apama_plugin_install
18:29:15 INFO  Dir:   plugin_apama/
18:29:15 INFO  Title: Validate apama plugin install
18:29:15 INFO  ==============================================================
18:29:16 WARN  Assertion that path exists=False for &quot;/etc/tedge/apama/project&quot; ... failed 
18:29:16 WARN  Executed sudo&lt;plugin_install&gt;, exit status 2
18:29:16 INFO  Contents of plugin_install.err: 
  ERROR: Device or resource busy (os error 16)
  -----

18:29:16 WARN  sudo&lt;plugin_install&gt; returned non-zero exit code 2 ... blocked [run.py:29]
18:29:16 WARN  Aborted test due to BLOCKED outcome
18:29:16 INFO  
18:29:16 INFO  cleanup:
18:29:16 INFO  Removing apama project
18:29:17 WARN  Executed sudo&lt;remove_apama_project&gt;, exit status 1
18:29:17 INFO  Contents of remove_apama_project.err: 
  rm: cannot remove '/etc/tedge/apama/project/logs/.nfs00000000001a190300003774': Device or resource busy
  -----

18:29:17 ERROR Error while running cleanup function: 
Traceback (most recent call last):
  File &quot;/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py&quot;, line 1305, in cleanup
    fn()
  File &quot;/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/environment_apama_plugin.py&quot;, line 144, in cleanup_project
    self.remove_project()
  File &quot;/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_apama/environment_apama_plugin.py&quot;, line 95, in remove_project
    stdouterr=&quot;remove_apama_project&quot;,
  File &quot;/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py&quot;, line 482, in startProcess
    abortOnError=abortOnError)
  File &quot;/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py&quot;, line 1401, in addOutcome
    self.abort(outcome, outcomeReason, callRecord)
  File &quot;/home/pi/env-pysys/lib/python3.7/site-packages/pysys/process/user.py&quot;, line 1420, in abort
    raise AbortExecution(outcome, outcomeReason, callRecord)
pysys.exceptions.AbortExecution: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1
18:29:17 WARN  Cleanup failed with 1 errors: Cleanup function failed: sudo&lt;remove_apama_project&gt; returned non-zero exit code 1 (AbortExecution) ... blocked 
18:29:17 INFO  
18:29:17 INFO  Test duration: 1.45 secs
18:29:17 INFO  Test final outcome:  BLOCKED
18:29:17 INFO  Test outcome reason: sudo&lt;plugin_install&gt; returned non-zero exit code 2 (+2 other failures)
18:29:17 INFO  
</system-out>
	</testcase>
</testsuite>
