<?xml version="1.0" encoding="utf-8"?>
<testsuite failures="1" name="docker_plugin_update" skipped="0" tests="1" time="38.37" timestamp="2022-05-02T11:21:20">
	<testcase classname="DockerPluginUpdateTest" name="docker_plugin_update">
		<failure message="BLOCKED: sudo&lt;plugin_install&gt; returned non-zero exit code 2 (+1 other failures)" type="BLOCKED"/>
		<system-out>11:20:41 INFO  ==============================================================
11:20:41 INFO  Id:    docker_plugin_update
11:20:41 INFO  Dir:   plugin_docker/
11:20:41 INFO  Title: Validate docker plugin install updates existing containers
11:20:41 INFO  ==============================================================
11:20:42 INFO  Executed sudo&lt;docker_images&gt;, exit status 0
11:20:42 INFO  Grep on file /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux/docker_images.out ... passed
11:21:06 INFO  Executed sudo&lt;docker_run&gt;, exit status 0, duration 23 secs
11:21:07 INFO  Executed sudo&lt;docker_ps&gt;, exit status 0
11:21:07 INFO  Grep on file /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux/docker_ps.out ... passed
11:21:12 WARN  Executed sudo&lt;plugin_install&gt;, exit status 2
11:21:12 WARN  sudo&lt;plugin_install&gt; returned non-zero exit code 2 ... blocked [environment_docker_plugin.py:136,environment_docker_plugin.py:144,run.py:30]
11:21:13 INFO  Executed sudo&lt;docker_ps_latest&gt;, exit status 0
11:21:14 INFO  Executed sudo&lt;docker_ps&gt;, exit status 0
11:21:14 INFO  Grep on file /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux/docker_ps.out ... passed
11:21:15 INFO  Executed sudo&lt;docker_ps&gt;, exit status 0
11:21:15 WARN  Grep on /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux/docker_ps.out contains &quot;registry:2.7.1&quot; ... failed [environment_docker_plugin.py:49,run.py:39]
11:21:15 INFO  
11:21:15 INFO  cleanup:
11:21:15 INFO  Removing containers scheduled to be cleaned up: ['2a6c21bb79c3', 'c0a453574e40', 'f0ad2c24d96ba23983baae739ed26150d0a996a5ae27daeb76f0d90fa0e735cb\n', '4d43c5c45869a0ecdbe6d3b5164853a7a9672f0a19818e81b7db38a91c41eb34\n', '7d1f78127437012f7ad503f13163b4991e13a02dab2cb784ac997dba4450d50d\n', '']
11:21:16 WARN  Executed sudo&lt;containers_for_cleanup&gt;, exit status 1
11:21:16 INFO  Removing images scheduled to be cleaned up: ['registry', 'registry', 'registry:2.7.1', 'registry', 'registry:2.7.1', 'registry:2.6.2', 'registry:2.7.1']
11:21:20 INFO  Executed sudo&lt;containers_for_cleanup&gt;, exit status 0
11:21:20 INFO  
11:21:20 INFO  Test duration: 38.37 secs
11:21:20 INFO  Test final outcome:  BLOCKED
11:21:20 INFO  Test outcome reason: sudo&lt;plugin_install&gt; returned non-zero exit code 2 (+1 other failures)
11:21:20 INFO  
</system-out>
	</testcase>
</testsuite>
