2022-04-27 10:31:15,137 INFO  ==============================================================
2022-04-27 10:31:15,138 INFO  Id:    runtime_start_two_mappers
2022-04-27 10:31:15,139 INFO  Dir:   tedge_mapper_c8y/
2022-04-27 10:31:15,140 INFO  Title: Validate two mappers can't be started at the same time
2022-04-27 10:31:15,141 INFO  ==============================================================
2022-04-27 10:31:15,721 WARN  Executed sudo<tedge_mapper1>, exit status 1
2022-04-27 10:31:15,726 INFO  Contents of tedge_mapper1.err: 
2022-04-27 10:31:15,728 INFO    Job for tedge-mapper-c8y.service failed because the control process exited with error code.
2022-04-27 10:31:15,728 INFO    See "systemctl status tedge-mapper-c8y.service" and "journalctl -xe" for details.
2022-04-27 10:31:15,729 INFO    -----
2022-04-27 10:31:15,730 INFO  
2022-04-27 10:31:15,752 WARN  sudo<tedge_mapper1> returned non-zero exit code 1 ... blocked [run.py:26]
2022-04-27 10:31:15,753 WARN  Aborted test due to BLOCKED outcome
2022-04-27 10:31:15,760 INFO  
2022-04-27 10:31:15,761 INFO  Test duration: 0.63 secs
2022-04-27 10:31:15,762 INFO  Test final outcome:  BLOCKED
2022-04-27 10:31:15,763 INFO  Test outcome reason: sudo<tedge_mapper1> returned non-zero exit code 1
2022-04-27 10:31:15,764 INFO  
